# Generated by Django 3.0.6 on 2021-05-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20210528_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='Category',
        ),
    ]
