# Generated by Django 3.0.6 on 2021-08-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
